server:
  port:
    8081
  servlet:
    context-path:/

spring:
  datasource:
    password: Apassword!1
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    url: jdbc:mariadb://localhost:3306/testdb?serverTimezone=UTC&characterEncoding=UTF-8

mybatis:
  mapper-locations: mapper/*.xml


bearer:
  authentication:
    header:
      value: E687D21D-F035-4F66-BB93-A336B8B267D0
      key: bearer
      name: API_TICKET

bean:
  services:
    - name: runtime-service1
      type: com.example.mybatis.demo.mybatisdemo.runtime.RuntimeServiceImpl1
    - name: runtime-service2
      type: com.example.mybatis.demo.mybatisdemo.runtime.RuntimeServiceImpl2
    - name: runtime-dbservice
      type: com.example.mybatis.demo.mybatisdemo.runtime.RuntimerServiceDbImpl1
    - name: webp-service
      type: com.example.mybatis.demo.webp.WebpServiceImpl